### PR TITLE
Improving Linking Compatibility with Newer Compiler Versions

### PR DESCRIPTION
**Pull request by jaredmulconry**
When marking student submissions, I found that the latest version of MSVC compiler could not link Raylib into their projects due to an incompatibility. This was likely caused by the sample's version of Raylib being compiled from source using default settings, which for Release included whole program optimisation. According to [this article on Microsoft's website](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-160), the /GL flag breaks binary compatibility.

I acquired the current release version of Raylib's sources, which was v3.0.0, released 1st April 2020. I compiled for all configurations and platforms, ensuring /GL was off and /Z7 was specified for Release configurations. The appropriate compiler (14.23.28105) was used based on what the software list says AIE supports, VS release 16.3.6.

In the process of testing the newly generated library files, I found an error in the AI_Wander sample that I corrected.
I also noticed that a lot of the folders containing build artifacts weren't in the gitignore, so I did a minor update to that to correctly reflect what should not be committed to the repo. Either of these secondary changes can be excluded, if so desired.

### CODE REVIEW

**Comment by jaredmulconry** [comment]
I forgot to specify in my original post, but this change only ensures compatibility within the v142 toolset. If we move to a newer major revision of MSVC and Visual Studio, binary compatibility is not guaranteed.

For the record, I built all samples in all configurations and for all platforms, to ensure everything built and linked correctly. I then ran every program generated under x86 Debug, x86 Release, x64 Release and the C# sample in Debug and Release. All ran cleanly.
I also tested with assessment submissions from my students, including 2 from AI for Games and 2 for Code Design & Data Structures. All built, linked and ran correctly after replacing the Raylib files with the new ones.

**Comment by samcsss** [comment]
This will take me a while to get to. Does someone else want to jump in and double check everything. 
This has the potential to affect all students, so another set of eyes on this would be awesome 
@terryn-aie can you help?

**Comment by terrehbyte** [comment]
Happy to validate~ Can I confirm that builds should function under all of the listed situations?

- Debug and Release
- x86 and x64
  - x86 builds should reference 32-bit raylib binaries
  - x64 builds should reference 64-bit raylib binaries
- Visual Studio 2019 16.4.2
  - v142 platform toolset

## Visual Studio Version
There's an inconsistency with the VS version between @jaredmulconry and I. the [2020 Courses page from IT](https://it.aie.edu/wiki/display/PORTFOLIO/2020+Courses) lists 16.4.2 for Visual Studio while Jared has listed 16.3.6. @samcsss , can you which version we should be working against?

## AnyCPU Configuration
Do I need to validate compatibility with the "AnyCPU" configuration? This is presumably introduced due to the presence of the "RaylibStarterCS" project, which can target "AnyCPU" (this is not supported by the C++ projects).

I'd prefer to just keep it to x86 and x64, if possible, to reduce the number of options available to students in the interest of minimizing complexity.

## Binary compatibility, moving forward
The article that Jared mentioned about [MSVC binary compatibility](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-160) suggests these binaries should be compatible with future versions of the 14X toolchain. Assuming that the next version in the VS202X line keeps to the 14X toolchain, we should be good.

## Next Steps
Once I've confirmed the above, I'll adjust some of the [GitHub Actions work that I've been doing](https://github.com/terrehbyte/AIEYear1Samples/runs/1444299836) to test for the configurations that mentioned above to at least ensure that the samples compile at minimum.

**Comment by samcsss** [comment]
We should definitely be using the version installed on student machines - the version I have on my list as the deployed version is 16.4.4
This will be what is deployed in AU next year, unless someone makes a good case for updating it - but that window may have already closed.
Both debug and release builds should compile. Ideally we want to aim for 32 and 64 bit versions too, but I'm fine to limit that to one of those if technically necessary.

'AnyCPU' no needed - just limit to x86 and x64

Is that enough to go off?

**Comment by jaredmulconry** [comment]
@terrehbyte Sorry for the inconsistency. I was previously directed to the 2020 Software Requests sheet on Teams for a record of what software was in use on-campus, which indicates 16.3.6 as the current version for 2020. I didn't know that IT wiki existed or that newer versions had been deployed since.
Thought it's an older toolset that I used, I'm hoping that by building it in a more forward compatible manner, that shouldn't cause issues. I'm happy to create an updated build of the libraries with a newer toolset, if desired.

I've been building every student's submission for AI for Games using these updated build files, and using the latest compiler release from microsoft (14.28.29333) with no issues on all configurations and all platforms (x86 & x64). I'm using VS 16.8.2 at home and have encountered no issues thus far.

**Comment by samcsss** [comment]
FYI, the goal of having all student samples in the same project was to ease maintenance - so when issues like this arise its much easier to update all the projects we're giving to students in one hit.
There is a private Teacher version of this repo - but maintaining that is less essential and that repo itself may be of limited value anyway

**Comment by terrehbyte** [comment]
> 
> 
> We should definitely be using the version installed on student machines - the version I have on my list as the deployed version is 16.4.4
> This will be what is deployed in AU next year, unless someone makes a good case for updating it - but that window may have already closed.
> Both debug and release builds should compile. Ideally we want to aim for 32 and 64 bit versions too, but I'm fine to limit that to one of those if technically necessary.
> 
> 'AnyCPU' no needed - just limit to x86 and x64
> 
> Is that enough to go off?

Yep, sounds good to me. The current commit (065fee2) works off of 16.4.2, but it should be a relatively quick change to switch it to 16.4.4 (just need to swap out the link to the build tools that we're relying on). 32-bit and 64-bit builds with both Debug and Release is good to go.

> 
> 
> FYI, the goal of having all student samples in the same project was to ease maintenance - so when issues like this arise its much easier to update all the projects we're giving to students in one hit.
> There is a private Teacher version of this repo - but maintaining that is less essential and that repo itself may be of limited value anyway

Yeah, that makes sense to me. Given our resources, the mono-repo approach feels like it works well enough for our needs.

> @terrehbyte Sorry for the inconsistency. I was previously directed to the 2020
> Software Requests sheet on Teams for a record of what software was in use
> on-campus, which indicates 16.3.6 as the current version for 2020. I didn't know
> that IT wiki existed or that newer versions had been deployed since. Thought
> it's an older toolset that I used, I'm hoping that by building it in a more
> forward compatible manner, that shouldn't cause issues. I'm happy to create an
> updated build of the libraries with a newer toolset, if desired.
> 
> I've been building every student's submission for AI for Games using these
> updated build files, and using the latest compiler release from microsoft
> (14.28.29333) with no issues on all configurations and all platforms (x86 &
> x64). I'm using VS 16.8.2 at home and have encountered no issues thus far.

No worries about the inconsistency -- Sam conjured up _another_ version (16.4.4) so that makes for a total of 3-4 different versions that we're compiling with at this point. 😅 I am a little concerned that the IT page differs from what Sam's image suggests, but if the image is the "truth" then I'm happy to roll with that.

No need for a new build of the Raylib binaries either: your builds should be forward-compatible w/ the compiler version that students are using, so you're good.

---

@samcsss, if there's nothing else, then I'll go ahead and validate the behavior of the samples that @jaredmulconry updated and then merge this PR if it all looks good.

> EDIT: In hindsight, adding the GitHub Actions code directly to master (prior to merging this PR) would have been ideal. 💦

**Review by terrehbyte — APPROVED** [review]
These changes look good to me.

The spelling of _Behavior_/_Behaviour_ is still inconsistent in other projects, but we can tackle that as a separate issue; this PR is focused on improving binary compatibility and fulfills its purpose.

**Comment by samcsss** [comment]
Every software list I've ever seen from IT has been wrong.
Always check a student machine if you need reliable info

**Pull request merged**
